### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by NtemKenyor** [IntergatedCircuits/HidSharp#11] opened 2022-01-18 03:17 UTC
I have tried all night to install this Application on my linux OS(Elementary Os) and it keeps giving the error that:

nuget restore -NonInteractive
WARNING: Error: SecureChannelFailure (The authentication or decryption has failed.)
Unable to find version '2.0.5' of package 'HidSharp'.

And below is the command
sudo make buildi

Please, I need a more detailed step-by-step approach on where to go from here or how to completely install the APp. I also feel that after this issue is resolved, I can make a better documentary about the Read.me file.

Thank you, 
I'm Ntem, Kenyor...

**Comment by benedekkupper** [comment] 2022-01-18 21:11
This sounds very much like a duplicate of #7, please follow-up on that ticket. Note that you'll need to contact the original author if you want to change anything about this library's Nuget configuration.

**Closed by benedekkupper** 2022-01-18 21:11 UTC
