### ISSUE TITLE
Any way to get HID category type?

### ISSUE THREAD

**Issue by wamk9** [IntergatedCircuits/HidSharp#32] opened 2024-04-02 10:23 UTC
Hi everyone!

I'm using HIDSharp 2.1 and i have a Arduino with 2 HID's, one is a Joystick and other a RawHID (without category), exists one way to get only the "RawHID", not the Joystick?

Thanks!

**Comment by benedekkupper** [comment] 2024-04-04 18:05
Duplicate of #16

**Closed by benedekkupper** 2024-04-04 18:05 UTC
